name: Daily Water Level Scrape

on:
  schedule:
    - cron: '0 11 * * *' # Runs daily at 11:00 UTC (which is 13:00 CEST)
  workflow_dispatch:
    # Allows you to manually trigger the workflow from the GitHub Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to push data back to the repo

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Or your preferred version, e.g., '3.10', '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y firefox
    
    - name: Install dependencies for Firefox
      run: |
        sudo apt-get install -y \
          libgtk-3-0 \
          libdbus-glib-1-2 \
          libx11-xcb1 \
          libxtst6 \
          libxrandr2 \
          libxss1 \
          libnss3 \
          libxcb-shm0 \
          libxcomposite1 \
          libxcursor1 \
          libxdamage1 \
          libxi6 \
          xauth \
          xvfb

    - name: Run Jadran.ba Scraper
      run: |
        python GH_jadranBA_scraper.py
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Pass the built-in GITHUB_TOKEN as GH_TOKEN

    - name: Run Vodostaji.hr Scraper
      run: |
        python GH_HRvode_scraper.py
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Pass the built-in GITHUB_TOKEN as GH_TOKEN

    - name: Print working directory
      if: failure()
      run: pwd && ls -la

    - name: Dump logs if failed
      if: failure()
      run: |
        echo "== Firefox crash log =="
        cat firefox.log || echo "No firefox.log found"

        echo "== Geckodriver log =="
        cat geckodriver.log || echo "No geckodriver.log found"

    - name: Commit and push changes (scraped data)
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add scraped_data_avpjm_jadran_ba/
        git add scraped_data_vodostaji_voda_hr/
        git commit -m "Automated daily water level data update" || echo "No changes to commit"
        git push || echo "No changes to push"

    # GitHub Actions will now only notify you on workflow failure by default.
