name: Daily Scraper

on:
  schedule:
    - cron: "0 11 * * *" # Runs daily at 11:00 UTC
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python with pip cache
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"
          cache: "pip"

      - name: Install dependencies except Firefox
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          sudo apt-get update
          sudo apt-get install -y \
            libgtk-3-0 libdbus-glib-1-2 libx11-xcb1 libxtst6 libxrandr2 \
            libxss1 libnss3 libxcb-shm0 libxcomposite1 libxcursor1 \
            libxdamage1 libxi6 xauth xvfb

      - name: Setup Firefox
        id: setup-firefox
        uses: browser-actions/setup-firefox@v1
        with:
          firefox-version: latest

      - name: Run scraper
        run: python GH_HRvode_scraper.py --firefox-path="${{ steps.setup-firefox.outputs.firefox-path }}"

      - name: Commit and push scraped data
        run: |
          git config --local user.name "GitHub Action"
          git config --local user.email "action@github.com"
          git pull --rebase --autostash
          git add HRvode_scraped_data/
          git commit -m "Daily scrape: $(date -u '+%Y-%m-%d')" || echo "Nothing to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git HEAD:main
