name: Daily Water Level Scrape

on:
  schedule:
    - cron: '0 11 * * *' # Runs daily at 11:00 UTC (which is 13:00 CEST)
  workflow_dispatch:
    # Allows you to manually trigger the workflow from the GitHub Actions tab

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed to push data back to the repo

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9' # Or your preferred version, e.g., '3.10', '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        sudo apt-get update
        sudo apt-get install -y firefox

  #  - name: Run Jadran.ba Scraper
   #   run: |
    #    python GH_jadranBA_scraper.py
     # env:
      #  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Pass the built-in GITHUB_TOKEN as GH_TOKEN

    - name: Run Vodostaji.hr Scraper
      run: |
        python GH_vodostajiHR_scraper.py
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Pass the built-in GITHUB_TOKEN as GH_TOKEN

    - name: Commit and push changes (scraped data)
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add scraped_data_avpjm_jadran_ba/
        git add scraped_data_vodostaji_voda_hr/
        git commit -m "Automated daily water level data update" || echo "No changes to commit"
        git push || echo "No changes to push"

    # GitHub Actions will now only notify you on workflow failure by default.
